version: "3"

services:

  app:
    container_name: euro2020
    image: hub.devfactory.ch/devfactory/docker-dev-images/php:8.0-laravel-dev-latest
    networks:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_DATABASE=euro2020
      - DB_PASSWORD=
      - LOG_CHANNEL=errorlog
    ports:
      - 3003:8000
    volumes:
      - ./:/app

  rr: &app
    build:
      context: .
      dockerfile: Dockerfile
    # image: euro2020
    user: "${APP_UID:-10001}:${APP_GID:-10001}"
    environment:
      PS1: '\[\033[1;32m\]\[\033[1;36m\][\u@\h] \[\033[1;34m\]\w\[\033[0;35m\] \[\033[1;36m\]# \[\033[0m\]'
      HOME: /tmp
      APP_DEBUG: 'true'
      APP_ENV: local
      APP_KEY: base64:wR8fsZA1nCPdq1fUOoaT99C3ghgbep8c6CG9ILsQ6Vo=
      REDIS_HOST: redis
      DB_HOST: mysql
      DB_DATABASE: euro2020
      DB_USERNAME: root
      DB_PASSWORD:
    ports:
      - 8090:8080
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # - tmp-data:/tmp:rw
      # - .:/app:rw
    networks:
      - mysql
      - redis

networks:
  mysql:
    external: true
  redis:
    external: true
